vulnerabilities:
  - id: CVE-2025-69720
    statement: "ncurses: we do not expose a TUI in any image."
  - id: CVE-2026-40356
    statement: "to this project unrelevant kerberos mechanism."
    expires: "2026-09-01"
