##### Build stage
FROM node:22.22.0-alpine3.23 AS build

RUN apk add --no-cache \
    chromium \
    nss \
    freetype \
    freetype-dev \
    harfbuzz \
    ca-certificates \
    ttf-freefont

ENV CHROME_BIN=/usr/bin/chromium-browser

WORKDIR /app

# 1. Dependencies
COPY ./frontend/package.json .
COPY ./frontend/package-lock.json .
RUN npm ci

# 2. Run tests
COPY ./frontend/tsconfig.json .
COPY ./frontend/angular.json .
COPY ./frontend/src/ src/
COPY VERSION src/assets/VERSION
COPY ./frontend/src/assets/hetida_designer_config_docker.json src/assets/hetida_designer_config.json
RUN npm run test-docker

# 3. Actual production build
ARG configuration=production
RUN npm run build -- --output-path=./dist/out --configuration $configuration

##### SBOM stage
# This stage generates an sbom for the node dependencies.
# This allows to regularly re-scan the image with trivy
FROM aquasec/trivy:0.70.0 AS sbom
WORKDIR /scan
COPY --from=build /app/package.json .
COPY --from=build /app/package-lock.json .
RUN trivy fs --format cyclonedx --output /sbom.cdx.json .

##### Production stage
FROM nginxinc/nginx-unprivileged:1.31.2-alpine3.23-slim as prod
COPY --from=build /app/dist/out/browser /usr/share/nginx/html
COPY --from=sbom /sbom.cdx.json /var/lib/sbom/sbom.cdx.json
COPY ./frontend/nginx.conf /etc/nginx/nginx.conf
EXPOSE 8080