##### Build and Test stage
FROM maven:3.8.6-openjdk-8-slim AS build
WORKDIR /usr/src/app
ENV MVN_SETTINGS=/usr/share/maven/ref/settings-docker.xml

# 1. Only update dependencies when the pom.xml actually changed.
COPY ./demo-adapter-java/pom.xml .
RUN mvn -s $MVN_SETTINGS dependency:go-offline

# 2. Do the actual build.
COPY ./demo-adapter-java/src src
RUN mvn -s $MVN_SETTINGS package

##### Production stage
FROM openjdk:8-jre-bullseye
RUN addgroup hdda_app && adduser --ingroup hdda_app hdda_app
USER hdda_app:hdda_app
WORKDIR /usr/app
COPY --from=build /usr/src/app/target/adapter.jar hetida-designer-demo-adapter-java.jar
EXPOSE 8091
ENTRYPOINT ["java", "-jar", "hetida-designer-demo-adapter-java.jar"]
