version: "3.5"

volumes:
  postgres_data:
    driver: local
  designer_obj_repo:
    driver: local

services:
  hetida-designer-frontend:
    image: hetida/designer-frontend
    ports:
      - 80:8080
    depends_on:
      - hetida-designer-backend

  hetida-designer-backend:
    image: hetida/designer-backend
    ports:
      - 8080:8090
    environment:
      - HD_DATABASE_URL=postgresql+psycopg2://hetida_designer_dbuser:hetida_designer_dbpasswd@hetida-designer-db:5432/hetida_designer_db
      - HD_ENSURE_DB_SCHEMA=true
      - HD_IS_RUNTIME_SERVICE=false      
    depends_on:
      - hetida-designer-db
      - hetida-designer-runtime

  hetida-designer-runtime:
    image: hetida/designer-runtime
    volumes:
      - designer_obj_repo:/mnt/obj_repo
      - ./runtime/demodata/local_files:/mnt/mounted_local_files
    ports:
      - 8090:8090
    environment:
      RUNTIME_LOCAL_FILE_ADAPTER_LOCAL_DIRECTORIES: '["/mnt/mounted_local_files"]'
      HD_IS_BACKEND_SERVICE: "false"

  hetida-designer-db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: hetida_designer_db
      POSTGRES_USER: hetida_designer_dbuser
      POSTGRES_PASSWORD: hetida_designer_dbpasswd

  hetida-designer-demo-adapter-java:
    image: hetida/designer-demo-adapter-java
    ports:
      - 8091:8091

  hetida-designer-demo-adapter-python:
    image: hetida/designer-demo-adapter-python
    ports:
      - 8092:8092

networks:
  default:
    name: hetida-designer-network