##### Base stage

# We explicitly target amd64 because our dependency stack is only tested and
# validated on this architecture. Building for other platforms may succeed but
# is unsupported.
ARG TARGETPLATFORM=linux/amd64
FROM --platform=${TARGETPLATFORM} python:3.14.3-slim-trixie AS base

ENV TIMEOUT=900

# Copy relevant files
COPY ./runtime/pipt_locks.env /app/pipt_locks.env
COPY ./runtime/pipt_config.env /app/pipt_config.env
COPY ./runtime/requirements-base.txt /app/requirements-base.txt
COPY ./runtime/requirements.txt /app/requirements.txt
COPY ./runtime/requirements-dev.txt /app/requirements-dev.txt
COPY ./runtime/pipt /app/pipt
COPY ./hdctl /hdctl

RUN apt-get -y update && apt-get -y install curl libpq-dev gcc libsnappy-dev && apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /app
ENV PIPT_PIP_INSTALL_ARGS="--no-cache-dir"
ENV PIPT_PIP_SYNC_PIP_ARGS="--no-cache-dir --no-deps"
RUN UV_NO_CACHE=true UV_COMPILE_BYTECODE=1 ./pipt sync-system --prod

##### Intermediate stage with actual application content
FROM base AS application_base
COPY ./runtime /app
COPY ./VERSION /app/VERSION
RUN chmod +x /app/start.sh

RUN mkdir -p /mnt/obj_repo
RUN chmod -R a+rw /mnt/obj_repo

RUN mkdir -p /mnt/autoimport
RUN chmod -R a+rw /mnt/autoimport


##### Test stage
# Note that in order to build the test stage you need to explicitly specify
# the test stage via
#     docker build --target test -f Dockerfile-runtime . -t hetdesrun_webservice
FROM application_base AS test
RUN ./pipt sync-system --dev
RUN python3 -m pytest --cov=hetdesrun --cov-report xml --junitxml test_results.xml tests
RUN bash /app/scripts/gen_ruff_report.sh


##### Pre-Prod stage
FROM application_base AS pre-prod
RUN useradd -m hd_app
USER hd_app
ENV HOST=0.0.0.0
ENV PORT=8090
EXPOSE 8090
CMD ["/app/start.sh"]

##### Syft stage - scan the complete production image
FROM anchore/syft:latest AS sbom-generator

# Copy the entire production filesystem to scan everything
COPY --from=pre-prod / /scan-target
# Generate SBOM of the complete production image
RUN ["/syft", "/scan-target",  "-o", "spdx-json=/tmp/sbom.spdx.json"]
RUN ["/syft", "/scan-target",  "-o", "syft-json=/tmp/sbom.syft.json"]
RUN ["/syft", "/scan-target",  "-o", "cyclonedx-json=/tmp/sbom.cyclonedx.json"]

##### Grype stage
FROM anchore/grype:latest AS grype-generator
COPY --from=sbom-generator /tmp /tmp
RUN ["/grype", "sbom:/tmp/sbom.syft.json",  "-o", "json=/tmp/grype-report.json"]
RUN ["/grype", "sbom:/tmp/sbom.syft.json",  "-o", "cyclonedx-json=/tmp/grype-report-cyclonedx.json"]

##### Production stage
# prod should be the default build, this is why we close with prod
FROM pre-prod AS prod
ENV HOST=0.0.0.0
ENV PORT=8090
EXPOSE 8090

# Copy SBOM and grype files
COPY --from=grype-generator /tmp/sbom.*.json ./sbom/
COPY --from=grype-generator /tmp/grype-*.json ./grype/
