version: "3"

volumes:
  postgres_data:
    driver: local
  designer_obj_repo:
    driver: local

services:
  hetida-designer-frontend:
    image: hetida/designer-frontend
    ports:
      - 80:80
    depends_on:
      - hetida-designer-backend

  hetida-designer-backend:
    image: hetida/designer-backend
    ports:
      - 8080:8080    
    environment:
      - org.hetida.designer.backend.installed.adapters=demo-adapter-python|Python-Demo-Adapter|http://localhost:8092|http://hetida-designer-demo-adapter-python:8092,demo-adapter-java|Java-Demo-Adapter|http://localhost:8091/adapter|http://hetida-designer-demo-adapter-java:8091/adapter,local-file-adapter|Local-File-Adapter|http://localhost:8090/adapters/localfile|http://hetida-designer-runtime:8090/adapters/localfile
    depends_on:
      - hetida-designer-db
      - hetida-designer-runtime

  hetida-designer-runtime:
    image: hetida/designer-runtime
    volumes:
      - designer_obj_repo:/mnt/obj_repo
      - ./runtime/demodata/local_files:/mnt/mounted_local_files
    ports:
      - 8090:8090
    environment:
      RUNTIME_LOCAL_FILE_ADAPTER_LOCAL_DIRECTORIES: '["/mnt/mounted_local_files"]'      


  hetida-designer-db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: hetida_designer_db
      POSTGRES_USER: hetida_designer_dbuser
      POSTGRES_PASSWORD: hetida_designer_dbpasswd

  hetida-designer-demo-adapter-java:
    image: hetida/designer-demo-adapter-java
    ports:
      - 8091:8091

  hetida-designer-demo-adapter-python:
    image: hetida/designer-demo-adapter-python
    ports:
      - 8092:8092