##### Base stage - build-time deps only
ARG TARGETPLATFORM=linux/amd64
FROM --platform=${TARGETPLATFORM} python:3.14.5-slim-trixie AS base
ENV TIMEOUT=900

COPY ./runtime/pipt_locks.env /app/pipt_locks.env
COPY ./runtime/pipt_config.env /app/pipt_config.env
COPY ./runtime/requirements-base.txt /app/requirements-base.txt
COPY ./runtime/requirements.txt /app/requirements.txt
COPY ./runtime/requirements-dev.txt /app/requirements-dev.txt
COPY ./runtime/pipt /app/pipt
COPY ./hdctl /hdctl

#### Python dependencies build-time deps
RUN apt-get -y update && apt-get -y install --no-install-recommends \
    libpq-dev \
    python3-dev \
    gcc \
    libsnappy-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
ENV PIPT_PIP_INSTALL_ARGS="--no-cache-dir"
ENV PIPT_PIP_SYNC_PIP_ARGS="--no-cache-dir --no-deps"
RUN UV_NO_CACHE=true UV_COMPILE_BYTECODE=1 ./pipt sync-system --prod

##### Only Python dependencies runtime deps
FROM --platform=${TARGETPLATFORM} python:3.14.5-slim-trixie AS runtime_base
ENV TIMEOUT=900

RUN apt-get -y update && apt-get -y install --no-install-recommends \
    libpq5 \
    libsnappy1v5 \
    && rm -rf /var/lib/apt/lists/*

COPY --from=base /usr/local/lib/python3.14 /usr/local/lib/python3.14
COPY --from=base /usr/local/bin /usr/local/bin

##### Intermediate stage with actual application content
FROM runtime_base AS application_base

COPY ./runtime /app
COPY ./VERSION /app/VERSION
COPY ./hdctl /hdctl

RUN chmod +x /app/start.sh
RUN mkdir -p /mnt/obj_repo && chmod -R a+rw /mnt/obj_repo
RUN mkdir -p /mnt/autoimport && chmod -R a+rw /mnt/autoimport

WORKDIR /app

##### Test stage, needs Python dependencies build-time deps to built dev dependencies
FROM base AS test
COPY ./runtime /app
COPY ./VERSION /app/VERSION
RUN chmod +x /app/start.sh

RUN UV_NO_CACHE=true UV_COMPILE_BYTECODE=1 ./pipt sync-system --dev
RUN python3 -m pytest --cov=hetdesrun --cov-report xml --junitxml test_results.xml tests
RUN bash /app/scripts/gen_ruff_report.sh

##### Pre-Prod stage
FROM application_base AS pre-prod
RUN useradd -m hd_app
USER hd_app
ENV PORT=8090
EXPOSE 8090
CMD ["/app/start.sh"]

##### Syft stage
FROM anchore/syft:latest AS sbom-generator
COPY --from=pre-prod / /scan-target
RUN ["/syft", "/scan-target", "-o", "spdx-json=/tmp/sbom.spdx.json"]
RUN ["/syft", "/scan-target", "-o", "syft-json=/tmp/sbom.syft.json"]
RUN ["/syft", "/scan-target", "-o", "cyclonedx-json=/tmp/sbom.cyclonedx.json"]

##### Grype stage
FROM anchore/grype:latest AS grype-generator
COPY --from=sbom-generator /tmp /tmp
RUN ["/grype", "sbom:/tmp/sbom.syft.json", "-o", "json=/tmp/grype-report.json"]
RUN ["/grype", "sbom:/tmp/sbom.syft.json", "-o", "cyclonedx-json=/tmp/grype-report-cyclonedx.json"]

##### Production stage
FROM pre-prod AS prod
COPY --from=grype-generator /tmp/sbom.*.json ./sbom/
COPY --from=grype-generator /tmp/grype-*.json ./grype/