volumes:
  postgres_data:
    driver: local
  designer_obj_repo:
    driver: local
  local_files:
    driver: local
  lgtm_data:

services:
  hetida-designer-frontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    #image: hetida/designer-frontend
    ports:
      - 80:8080
    depends_on:
      hetida-designer-backend:
        condition: service_started
      hetida-designer-demo-adapter-python:
        condition: service_started

  hetida-designer-backend:
    build:
      context: .
      dockerfile: Dockerfile-runtime
    #image: hetida/designer-backend
    ports:
      - 8080:8090
    environment:
      - HD_DATABASE_URL=postgresql+psycopg://hetida_designer_dbuser:hetida_designer_dbpasswd@hetida-designer-db:5432/hetida_designer_db
      - HD_ENSURE_DB_SCHEMA=true
      - HD_IS_RUNTIME_SERVICE=false
      - HD_USE_AUTH=false
      - MAX_WORKERS=1
      #- LOG_LEVEL=DEBUG
      - LOG_HTTPX=true
      - HETIDA_DESIGNER_PURE_UVICORN=true
      #- LOG_DIRECT_PROVISIONING_OUTPUTS=true
      - HD_OTEL_VIA_LOGFIRE_ACTIVE=true
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://grafana-otel-lgtm:4318
      - OTEL_SERVICE_NAME=hetida-designer-backend

    healthcheck:
      test: curl --fail http://hetida-designer-backend:8090/api/info || exit 1
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 60s
    depends_on:
      hetida-designer-db:
        condition: service_healthy
      hetida-designer-runtime:
        condition: service_started

  hetida-designer-runtime:
    build:
      context: .
      dockerfile: Dockerfile-runtime
    #image: hetida/designer-runtime
    restart: always
    ports:
      - 8090:8090
    volumes:
      - designer_obj_repo:/mnt/obj_repo
      - ./runtime/demodata/local_files:/mnt/mounted_local_files
    environment:
      RUNTIME_LOCAL_FILE_ADAPTER_LOCAL_DIRECTORIES: '["/mnt/mounted_local_files"]'
      HD_IS_BACKEND_SERVICE: "false"
      HD_USE_AUTH: "false"
      MAX_WORKERS: 1
      #LOG_LEVEL: "DEBUG"
      LOG_HTTPX: "true"
      HETIDA_DESIGNER_PURE_UVICORN: "true"
      #LOG_DIRECT_PROVISIONING_OUTPUTS: "true"
      HD_OTEL_VIA_LOGFIRE_ACTIVE: "true"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://grafana-otel-lgtm:4318"
      OTEL_SERVICE_NAME: "hetida-designer-runtime"

  grafana-otel-lgtm:
    image: grafana/otel-lgtm:0.28.0
    container_name: lgtm
    ports:
      - "3000:3000" # Grafana UI
      - "3200:3200" # Tempo API
      - "4317:4317" # OTLP gRPC
      - "4318:4318" # OTLP HTTP
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
    volumes:
      - lgtm_data:/data
    restart: unless-stopped
    healthcheck:
      test:
        ["CMD-SHELL", "wget -qO- http://localhost:3000/api/health | grep ok"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 15s

  hetida-designer-db:
    image: postgres:latest
    ports:
      - 5430:5432
    volumes:
      - postgres_data:/var/lib/postgresql
    environment:
      POSTGRES_DB: hetida_designer_db
      POSTGRES_USER: hetida_designer_dbuser
      POSTGRES_PASSWORD: hetida_designer_dbpasswd

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U hetida_designer_dbuser -d hetida_designer_db",
        ]
      interval: 5s
      timeout: 5s
      retries: 5

  hetida-designer-demo-adapter-python:
    build:
      context: .
      dockerfile: Dockerfile-demo-adapter-python
    image: hetida/designer-demo-adapter-python
    ports:
      - 8092:8092

networks:
  default:
    name: hetida-designer-network
