import datetime
import io
import json
import logging
from collections import defaultdict
from enum import StrEnum
from types import NoneType, UnionType
from typing import Annotated, Any, Literal, TypedDict
from uuid import UUID

import msgspec
import numpy as np
import pandas as pd
import pytz
from hdhelpers.helpers import modify_timezone  # noqa F401  # noqa F401  # noqa F401
from plotly.graph_objects import Figure
from pydantic import (
    BaseModel,
    BeforeValidator,
    ConfigDict,
    Field,
    PlainSerializer,
    PlainValidator,
    ValidationError,
    ValidatorFunctionWrapHandler,
    WrapValidator,
    create_model,
)

logger = logging.getLogger(__name__)

MULTITSFRAME_COLUMN_NAMES = ["timestamp", "metric", "value"]
SINGLETSFRAME_COLUMN_NAMES = ["timestamp", "value"]


class ComponentException(Exception):
    """Exception to re-raise exceptions with error code raised in the component code."""

    __is_hetida_designer_exception__ = True

    def __init__(
        self,
        *args: Any,
        error_code: int | str = "",
        extra_information: dict | None = None,
        **kwargs: Any,
    ) -> None:
        if not isinstance(error_code, int | str):
            raise ValueError("The ComponentException.error_code must be int or string!")
        self.error_code = error_code
        self.extra_information = extra_information
        super().__init__(*args, **kwargs)


class ComponentInputValidationException(ComponentException):
    """In code input validation failures"""

    def __init__(
        self,
        *args: Any,
        invalid_component_inputs: list[str],
        error_code: int | str = "",
        **kwargs: Any,
    ) -> None:
        super().__init__(
            *args,
            error_code=error_code,
            extra_information={"invalid_component_inputs": invalid_component_inputs},
            **kwargs,
        )


class InsufficientPlottingData(ComponentException):
    """A plot component has insufficient data to generate a meaningful plot

    This exception class should be used when custom plots generated by hetida
    designer are integrated in other frontends. This allows the frontend to
    handle the case of e.g. no data to show in a sensible way, surpressing an
    empty plot and showing an adequate message instead.
    """


class IntentionallyAbortedExecution(ComponentException):
    """Execution of this component or workflow is intentionally aborted

    Often execution of a workflow should stop if a certain condition is not
    fulfilled. This can of course be done by raising an exception. To communicate
    this intention to 3rd party systems and make it clear that this is not an actual error
    situation it is recommended to use this exception.
    """


class PlotTargetSettings(BaseModel):
    """Settings that plot components can/should use

    Some Plotly settings like locale or the timezone of timestamps must be set
    by Python and cannot easily be set by plotly.js in a frontend.

    They can be provided to execution endpoints as part of the ExecByIdBase payload,
    are made accessible to components using the execution context.

    hdutils provides helper functions to access them at runtime.
    """

    plot_target_timezone: str | None = Field(
        None,
        description=(
            "The timezone plot components should use for datetime axes etc."
            " Usually via"
            " s.index=pd.to_datetime(s.index, utc=True).tz_convert(plot_target_timezone)"
        ),
        examples=["Europe/Berlin"],
    )
    plot_target_locale: str | None = Field(
        None,
        description=(
            "Locale to set for plots, e.g. to write weekdays in the user's language."
            " This has to be set in the config of the plotly figure dict and the plotly.js "
            "must have the associated plotly local scripts loaded."
        ),
    )
    target_darkmode: bool = Field(
        False, description="Whether plots should be layouted/configured for darkmode"
    )
    datetime_tick_format: str | None = Field(
        None, description="Tickformat to use for datetime axes", examples=["%H:%M<br>%d.%m.%Y"]
    )
    datetime_x_axes_range_start: datetime.datetime | None = Field(
        None, description="datetime range start which plots should set as x axis range"
    )

    datetime_x_axes_range_end: datetime.datetime | None = Field(
        None, description="datetime range end which plots should set as x axis range"
    )


def get_plot_target_settings() -> PlotTargetSettings:
    """Obtain plot settings from runtime execution context.

    If hetdesrun is not importable or this context field is not set,
    return default values.
    """
    try:
        from hetdesrun.runtime.context import get_runtime_exec_context

        return get_runtime_exec_context().plot_target_settings
    except ImportError:
        logger.warning("Could not load runtime exec context, import failed! Switch to defaults.")
        # return defaults if hetdesrun is not available as import
        return PlotTargetSettings()


class WrappedModelWithCustomObjects(BaseModel):
    model: Any = None
    custom_objects: dict[str, Any]


class MetaDataWrapped(BaseModel):
    """Allows to wrap pandas object data with metadata"""

    hd_wrapped_data_object__: Literal["SERIES", "DATAFRAME"] = Field(
        ..., alias="__hd_wrapped_data_object__"
    )
    metadata__: dict[str, Any] = Field(
        ...,
        alias="__metadata__",
        description="Json serializable dictionary of metadata. Will be written"
        "to the resulting pandas object's attrs attribute.",
    )
    data__: dict | list = Field(
        ...,
        alias="__data__",
        description="The actual data which constitutes the pandas object.",
    )
    data_parsing_options__: dict = Field(
        {},
        alias="__data_parsing_options__",
        description=(
            "Additional options for parsing the provided data."
            " For example, setting orient to one of the allowed values for the respective"
            " Pandas type allows to use different json representations for the actual data."
        ),
    )

    model_config = ConfigDict(
        serialize_by_alias=True, validate_by_alias=True, validate_by_name=True
    )


def try_parse_wrapped(
    data: str | dict | list,
    hd_wrapped_data_object: Literal["SERIES", "DATAFRAME"],
) -> MetaDataWrapped:
    if isinstance(data, str):
        wrapped_data = MetaDataWrapped.model_validate_json(data)

        if wrapped_data.hd_wrapped_data_object__ != hd_wrapped_data_object:
            msg = (
                f"Unexpected hd model type: {wrapped_data.hd_wrapped_data_object__}."
                f" Expected {hd_wrapped_data_object}"
            )
            logger.warning(msg)
            raise TypeError(msg)
    else:
        wrapped_data = MetaDataWrapped.model_validate(data)

    return wrapped_data


def parse_wrapped_content(
    v: str | dict | list,
    wrapped_data_object: Literal["SERIES", "DATAFRAME"],
) -> tuple[str | dict | list, None | dict[str, Any], dict[str, Any]]:
    data_content: str | dict | list
    try:
        wrapped_object = try_parse_wrapped(v, wrapped_data_object)
        parsed_metadata = wrapped_object.metadata__
        data_content = wrapped_object.data__
        parsing_options = wrapped_object.data_parsing_options__
    except (ValidationError, TypeError) as e:
        logger.debug("Data object is not wrapped: %s", str(e))
        data_content = v
        parsed_metadata = None
        parsing_options = {}

    return data_content, parsed_metadata, parsing_options


def wrap_metadata_as_attrs(
    data_object: pd.Series | pd.DataFrame, metadata: None | dict[str, Any]
) -> pd.Series | pd.DataFrame:  # TODO: make generic: input type = output type
    if metadata is not None:
        data_object.attrs = metadata
    else:
        data_object.attrs = {}
    return data_object


def parse_pandas_data_content(
    data_content: str | dict | list, typ: Literal["series", "frame"], parsing_options: dict
) -> pd.DataFrame | pd.Series:
    try:
        if isinstance(data_content, str):
            parsed_pandas_object = pd.read_json(
                io.StringIO(data_content), typ=typ, **parsing_options
            )
        else:
            parsed_pandas_object = pd.read_json(data_content, typ=typ, **parsing_options)

    except Exception:  # noqa: BLE001
        try:
            parsed_pandas_object = pd.read_json(
                io.StringIO(json.dumps(data_content)), typ=typ, **parsing_options
            )

        except Exception as read_json_exception:  # noqa: BLE001
            raise ValueError(
                "Could not parse provided input as Pandas "
                + ("Series" if typ == "series" else "DataFrame")
            ) from read_json_exception

    return parsed_pandas_object


class DataType(StrEnum):
    """hetida designer data types

    These are the types available for component/workflow inputs/outputs.
    """

    Integer = "INT"
    Float = "FLOAT"
    String = "STRING"
    DataFrame = "DATAFRAME"
    Series = "SERIES"
    MultiTSFrame = "MULTITSFRAME"
    SingleTSFrame = "SINGLETSFRAME"
    Boolean = "BOOLEAN"
    Any = "ANY"
    PlotlyJson = "PLOTLYJSON"


def parse_pydantic_series(v: pd.Series | str | dict | list) -> pd.Series:
    """Custom pydantic Data Type for parsing Pandas Series

    Parses either a json string according to pandas.read_json
    with typ="series" and default arguments otherwise or
    a Python dict-like data structure using the constructor
    of the pandas.Series class with default arguments.

    Also allows a wrapped variant where metadata can be provided.

    Examples of valid input:
        '{"0":1.0,"1":2.1,"2":3.2}'
        {"0":1.0,"1":2.1,"2":3.2}
        [1.2, 3.5, 2.9]
        '[1.2, 3.5, 2.9]'

    """
    if isinstance(v, pd.Series):
        return v

    if not isinstance(
        v, str | dict | list
    ):  # need to check at runtime since we get objects from user code
        msg = f"Got unexpected type at runtime when parsing Series: {str(type(v))}"
        logger.error(msg)
        raise ValueError(msg)

    data_content, metadata, parsing_options = parse_wrapped_content(v, "SERIES")

    return wrap_metadata_as_attrs(
        parse_pandas_data_content(data_content, "series", parsing_options), metadata
    )


def serialize_series(s: pd.Series) -> dict[str, Any]:
    return {
        "__hd_wrapped_data_object__": "SERIES",
        "__metadata__": s.attrs,
        "__data__": json.loads(
            # double serialization/deserialization in order to serialize both NaN and NaT
            # to null
            s.to_json(
                date_format="iso",
                orient="split",
                # orient="split" serialization is the only way pandas keeps duplicate index
                #  (with possibly different values) entries for Series objects!
            )
        ),
        "__data_parsing_options__": {"orient": "split"},
    }


PydanticPandasSeries = Annotated[
    pd.Series,
    PlainSerializer(serialize_series),
    BeforeValidator(parse_pydantic_series),
]


def parse_pydantic_pandas_data_frame(v: pd.DataFrame | str | dict | list) -> pd.DataFrame:
    """Custom pydantic Data Type for parsing Pandas DataFrames

    Parses either a json string according to pandas.read_json
    with typ="frame" and default arguments otherwise or
    a Python dict-like data structure using the constructor
    of the pandas.DataFrame class with default arguments.

    Additionally a MetaDataWrapped variant of these can be parsed
    and then is equipped with the provided metadata in the `attrs`
    attribute (https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.attrs.html
    """
    if isinstance(v, pd.DataFrame):
        return v

    if not isinstance(
        v, str | dict | list
    ):  # need to check at runtime since we get objects from user code
        msg = f"Got unexpected type at runtime when parsing DataFrame: {str(type(v))}"
        logger.error(msg)
        raise ValueError(msg)

    data_content, metadata, parsing_options = parse_wrapped_content(v, "DATAFRAME")

    return wrap_metadata_as_attrs(
        parse_pandas_data_content(data_content, "frame", parsing_options), metadata
    )


def serialize_dataframe(df: pd.DataFrame) -> dict[str, Any]:
    return {
        "__hd_wrapped_data_object__": "DATAFRAME",
        "__metadata__": df.attrs,
        "__data__": json.loads(
            df.to_json(date_format="iso")  # in order to serialize both NaN and NaT to null
        ),
    }


PydanticPandasDataFrame = Annotated[
    pd.DataFrame,
    PlainSerializer(serialize_dataframe),
    BeforeValidator(parse_pydantic_pandas_data_frame),
]


def validate_multits_properties(  # noqa:PLR0912
    df: pd.DataFrame,
) -> pd.DataFrame:
    if len(df.columns) == 0:
        attrs = df.attrs
        df = pd.DataFrame(columns=MULTITSFRAME_COLUMN_NAMES)
        df.attrs = attrs

    if len(df.columns) < 3:
        raise ValueError(
            "MultiTSFrame requires at least 3 columns: metric, timestamp"
            f" and at least one additional columns. Only found {str(df.columns)}"
        )

    if not ({"metric", "timestamp"}.issubset(set(df.columns))):
        column_names_string = ", ".join(df.columns)
        raise ValueError(
            f"The column names {column_names_string} don't contain required columns"
            ' "timestamp" and "metric" for a MultiTSFrame.'
        )

    if df["metric"].isna().any():
        raise ValueError("No null values are allowed for the column 'metric' of a MulitTSFrame.")

    df["metric"] = df["metric"].astype("string")

    if df["timestamp"].isna().any():
        raise ValueError("No null values are allowed for the column 'timestamp' of a MulitTSFrame.")

    if len(df.index) == 0:
        df["timestamp"] = pd.to_datetime(df["timestamp"], utc=True)

    if not isinstance(df["timestamp"].dtype, pd.DatetimeTZDtype):
        raise ValueError(
            "Column 'timestamp' of MultiTSFrame does not have DatetimeTZDtype dtype. "
            f"Got {str(df['timestamp'].dtype)} index dtype instead."
        )

    if df["timestamp"].dt.tz not in (pytz.UTC, datetime.timezone.utc):
        raise ValueError(
            "Column 'timestamp' of MultiTSFrame does not have UTC timezone. "
            f"Got {str(df['timestamp'].dt.tz)} timezone instead."
        )

    return df.sort_values("timestamp")


def parse_pydantic_multi_timeseries_pandas_data_frame(
    v: pd.DataFrame | str | dict | list,
) -> pd.DataFrame:
    if isinstance(v, pd.DataFrame):
        return v

    if not isinstance(
        v, str | dict | list
    ):  # need to check at runtime since we get objects from user code
        msg = f"Got unexpected type at runtime when parsing MultiTsFrame: {str(type(v))}"
        logger.error(msg)
        raise ValueError(msg)

    data_content, metadata, parsing_options = parse_wrapped_content(v, "DATAFRAME")

    new_df = wrap_metadata_as_attrs(
        parse_pandas_data_content(data_content, "frame", parsing_options), metadata
    )

    return validate_multits_properties(new_df)


def serialize_multitsframe(df: pd.DataFrame) -> dict[str, Any]:
    return {
        "__hd_wrapped_data_object__": "DATAFRAME",
        "__metadata__": df.attrs,
        "__data__": json.loads(
            df.to_json(date_format="iso")
        ),  # in order to serialize both NaN and NaT to null
    }


PydanticMultiTimeseriesPandasDataFrame = Annotated[
    pd.DataFrame,
    PlainSerializer(serialize_multitsframe),
    BeforeValidator(parse_pydantic_multi_timeseries_pandas_data_frame),
]


def validate_singlets_properties(
    df: pd.DataFrame,
) -> pd.DataFrame:
    """Validate the conventions of a SingleTSFrame

    A SingleTSFrame holds a single — possibly multi-dimensional — timeseries. It has the same
    tabular representation as a MultiTSFrame, except that it has no "metric" column, since
    the metric is unique for the whole frame. Every column besides "timestamp" is a value
    dimension. This explicitly includes a column named "metric", which is treated like any
    other value column here.
    """
    if len(df.columns) == 0:
        attrs = df.attrs
        df = pd.DataFrame(columns=SINGLETSFRAME_COLUMN_NAMES)
        df.attrs = attrs

    if len(df.columns) < 2:
        raise ValueError(
            "SingleTSFrame requires at least 2 columns: timestamp"
            f" and at least one value column. Only found {str(df.columns)}"
        )

    if "timestamp" not in df.columns:
        column_names_string = ", ".join(df.columns)
        raise ValueError(
            f"The column names {column_names_string} don't contain the required column"
            ' "timestamp" for a SingleTSFrame.'
        )

    if df["timestamp"].isna().any():
        raise ValueError(
            "No null values are allowed for the column 'timestamp' of a SingleTSFrame."
        )

    if len(df.index) == 0:
        df["timestamp"] = pd.to_datetime(df["timestamp"], utc=True)

    if not isinstance(df["timestamp"].dtype, pd.DatetimeTZDtype):
        raise ValueError(
            "Column 'timestamp' of SingleTSFrame does not have DatetimeTZDtype dtype. "
            f"Got {str(df['timestamp'].dtype)} index dtype instead."
        )

    if df["timestamp"].dt.tz not in (pytz.UTC, datetime.timezone.utc):
        raise ValueError(
            "Column 'timestamp' of SingleTSFrame does not have UTC timezone. "
            f"Got {str(df['timestamp'].dt.tz)} timezone instead."
        )

    return df.sort_values("timestamp")


def parse_pydantic_single_timeseries_pandas_data_frame(
    v: pd.DataFrame | str | dict | list,
) -> pd.DataFrame:
    if isinstance(v, pd.DataFrame):
        return v

    if not isinstance(
        v, str | dict | list
    ):  # need to check at runtime since we get objects from user code
        msg = f"Got unexpected type at runtime when parsing SingleTsFrame: {str(type(v))}"
        logger.error(msg)
        raise ValueError(msg)

    data_content, metadata, parsing_options = parse_wrapped_content(v, "DATAFRAME")

    new_df = wrap_metadata_as_attrs(
        parse_pandas_data_content(data_content, "frame", parsing_options), metadata
    )

    return validate_singlets_properties(new_df)


def serialize_singletsframe(df: pd.DataFrame) -> dict[str, Any]:
    return {
        "__hd_wrapped_data_object__": "DATAFRAME",
        "__metadata__": df.attrs,
        "__data__": json.loads(
            df.to_json(date_format="iso")
        ),  # in order to serialize both NaN and NaT to null
    }


PydanticSingleTimeseriesPandasDataFrame = Annotated[
    pd.DataFrame,
    PlainSerializer(serialize_singletsframe),
    BeforeValidator(parse_pydantic_single_timeseries_pandas_data_frame),
]


# "Raw" serializer variants: Previously we parsed pandas output JSON back with json.loads to
# ensure having a json serializable object at the service boundary later and avoiding having
# 5xx errors. At that boundary it was re-encoded leading to multiple serialization loops.
# Now msgspec.Raw is used to both ensure json serializability and keep the generated bytes
# avoiding further such loops
#
# A dict containing ``msgspec.Raw`` values MUST be encoded with msgspec directly; it cannot be
# routed through pydantic's ``model_dump(mode="json")`` (which does not understand ``Raw``).


def serialize_series_raw(s: pd.Series) -> dict[str, Any]:
    return {
        "__hd_wrapped_data_object__": "SERIES",
        # __metdata__ uncoerced on purpose; the msgspec enc_hook coerces exotic values
        # (see hetdesrun.service.serialization_helpers):
        "__metadata__": s.attrs,
        "__data__": msgspec.Raw(
            s.to_json(
                date_format="iso",
                orient="split",
                # orient="split" is the only way pandas keeps duplicate index entries for Series
            ).encode()
        ),
        "__data_parsing_options__": {"orient": "split"},
    }


def serialize_dataframe_raw(df: pd.DataFrame) -> dict[str, Any]:
    return {
        "__hd_wrapped_data_object__": "DATAFRAME",
        "__metadata__": df.attrs,
        "__data__": msgspec.Raw(df.to_json(date_format="iso").encode()),
    }


# MultiTSFrames and SingleTSFrames use the same wrapper as ordinary DataFrames.
serialize_multitsframe_raw = serialize_dataframe_raw
serialize_singletsframe_raw = serialize_dataframe_raw


def parse_any(v: Any) -> Any:
    """Tries to parse Any objects somehow intelligently

    Reason is that an object may be provided by the backend either as a proper json-object directly
    in some cases (dict-like objects) or as json-encoded string (happens for example for lists).

    Sometimes, if the frontend is involved, json strings get even double-string-encoded! This is a
    known bug of frontend-backend-runtime interaction.

    Sometimes adapter implementations deliver ANY-data directly as json objects and othertimes
    string-encoded.

    As a workaround for all these cases this class tries to json-parse a string if it receives one
    and only if that does not work it yields the actual string value. If it works and the result is
    itself a string again it tries to json-decode a second time and returns the result if that
    works. Otherwise it returns the result string of the first parsing.

    This workaround is justified by the argument that the user should really use a STRING input if
    a string is expected and not an ANY input. Likewise, adapters should offer string data as STRING
    data sources and not as ANY data sources.
    """
    if isinstance(v, str):
        # try to parse string as json
        try:
            parsed_json_object = json.loads(v)
        except json.decoder.JSONDecodeError:
            logger.info(
                "Could not JSON-parse string %s in Any input."
                " Therefore treating it as actual string value",
                v[:30] + "..." if len(v) > 10 else v,
            )
            return v

        if isinstance(
            parsed_json_object, str
        ):  # sometimes it even gets double-encoded for some reasons
            try:
                parsed_json_object = json.loads(parsed_json_object)
            except json.decoder.JSONDecodeError:
                logger.info(
                    "Could not JSON-parse string %s in Any input. "
                    " Therefore treating it as actual string value",
                    parsed_json_object[:30] + "..." if len(v) > 10 else v,
                )
                return parsed_json_object

        return parsed_json_object
    return v


ParsedAny = Annotated[
    Any,
    BeforeValidator(parse_any),
]


def parse_plotly_json_dict(v: dict) -> dict:
    if isinstance(v, dict):
        # TODO: check structure more thoroughly
        return v

    raise ValueError("Plotly JSON is not a dict object.")


ParsedPlotly = Annotated[dict, PlainValidator(parse_plotly_json_dict)]


def wrap_basic_type_parsing(
    value: Any, handler: ValidatorFunctionWrapHandler, basic_type: type
) -> Any:
    pydantic_parsed_basic_type = handler(value)

    if isinstance(value, basic_type) and value == pydantic_parsed_basic_type:
        return value  # original value to preserve idempotency.
    # Avoids pydantic attribute copying as well.

    return pydantic_parsed_basic_type


ParsedFloat = Annotated[
    float,
    WrapValidator(lambda value, handler: wrap_basic_type_parsing(value, handler, basic_type=float)),
]

ParsedInt = Annotated[
    int,
    WrapValidator(lambda value, handler: wrap_basic_type_parsing(value, handler, basic_type=int)),
]

ParsedBool = Annotated[
    bool,
    WrapValidator(lambda value, handler: wrap_basic_type_parsing(value, handler, basic_type=bool)),
]

ParsedStr = Annotated[
    str,
    WrapValidator(lambda value, handler: wrap_basic_type_parsing(value, handler, basic_type=str)),
]

data_type_map: dict[DataType | None, type] = {
    DataType.Integer: ParsedInt,
    DataType.Float: ParsedFloat,
    DataType.String: ParsedStr,
    DataType.Series: PydanticPandasSeries,
    DataType.MultiTSFrame: PydanticMultiTimeseriesPandasDataFrame,
    DataType.SingleTSFrame: PydanticSingleTimeseriesPandasDataFrame,
    DataType.DataFrame: PydanticPandasDataFrame,
    DataType.Boolean: ParsedBool,
    # Any as Type is the correct way to tell pydantic how to parse an arbitrary object:
    DataType.Any: ParsedAny,
    DataType.PlotlyJson: ParsedPlotly,
    None: NoneType,
}

optional_data_type_map: dict[DataType | None, Any] = {
    DataType.Integer: ParsedInt | None,
    DataType.Float: ParsedFloat | None,
    DataType.String: ParsedStr | None,
    DataType.Series: PydanticPandasSeries | None,
    DataType.MultiTSFrame: PydanticMultiTimeseriesPandasDataFrame | None,
    DataType.SingleTSFrame: PydanticSingleTimeseriesPandasDataFrame | None,
    DataType.DataFrame: PydanticPandasDataFrame | None,
    DataType.Boolean: ParsedBool | None,
    # Any as Type is the correct way to tell pydantic how to parse an arbitrary object:
    DataType.Any: ParsedAny | None,
    DataType.PlotlyJson: ParsedPlotly | None,
    None: NoneType | None,
}


def serialize_plotly_fig(v: dict[str, Any] | Figure) -> Any:
    if isinstance(v, dict):
        return v

    # possibly quite inefficient (multiple serialisation / deserialization) but
    # guarantees that the PlotlyJSONEncoder is used and so the resulting Json
    # should be definitely compatible with the plotly javascript library:

    # Whats the difference using json.loads(json.dumps(fig_dict_obj, cls=PlotlyJSONEncoder))
    # or employing fig.to_plotly_json()
    return json.loads(v.to_json(validate=False))


serializer_funcs_by_type = {
    pd.Series: serialize_series,
    pd.DataFrame: lambda v: {
        "__hd_wrapped_data_object__": "DATAFRAME",
        "__metadata__": v.attrs,
        "__data__": json.loads(
            v.to_json(date_format="iso")  # in order to serialize both NaN and NaT to null
        ),
    },
    PydanticPandasSeries: serialize_series,
    PydanticPandasDataFrame: lambda v: {
        "__hd_wrapped_data_object__": "DATAFRAME",
        "__metadata__": v.attrs,
        "__data__": json.loads(
            v.to_json(date_format="iso")  # in order to serialize both NaN and NaT to null
        ),
    },
    PydanticMultiTimeseriesPandasDataFrame: lambda v: {
        "__hd_wrapped_data_object__": "DATAFRAME",
        "__metadata__": v.attrs,
        "__data__": json.loads(
            v.to_json(date_format="iso")
        ),  # in order to serialize both NaN and NaT to null
    },
    PydanticSingleTimeseriesPandasDataFrame: lambda v: {
        "__hd_wrapped_data_object__": "DATAFRAME",
        "__metadata__": v.attrs,
        "__data__": json.loads(
            v.to_json(date_format="iso")
        ),  # in order to serialize both NaN and NaT to null
    },
    np.ndarray: lambda v: v.tolist(),
    datetime.datetime: lambda v: v.isoformat(),
    UUID: lambda v: str(v),  # alternatively: v.hex
    Figure: serialize_plotly_fig,  # lambda v: json.loads(json.dumps(v.to_plotly_json(), cls=PlotlyJSONEncoder)),
    NoneType: lambda x: x,
    None: lambda x: x,
}


# Only the pandas payload types get the ``msgspec.Raw`` splicing treatment (they are the large ones
# and the only ones that paid the json.loads round-trip). Every other output type is left uncoerced
# and handed straight to the encoder, whose ``enc_hook`` (pydantic's ``to_jsonable_python``) coerces
# any exotic values in a single encode pass - so numpy scalars, plotly dicts, datetimes etc.
# serialize (and fail) exactly as pydantic's ``model_dump(mode="json")`` did.
raw_pandas_serializer_funcs_by_type = {
    PydanticPandasSeries: serialize_series_raw,
    PydanticPandasDataFrame: serialize_dataframe_raw,
    PydanticMultiTimeseriesPandasDataFrame: serialize_multitsframe_raw,
    PydanticSingleTimeseriesPandasDataFrame: serialize_singletsframe_raw,
}


def serialize_output_results_raw(
    output_results_by_output_name: dict[str, Any],
    output_types_by_output_name: dict[str, DataType | None],
) -> dict[str, Any]:
    """Raw-splicing counterpart of ``WorkflowExecutionInfo.serialize_output_result_dict``.

    Dispatches by declared output data type: pandas payloads become the ``msgspec.Raw`` wrapper
    (skipping the ``json.loads(df.to_json())`` round-trip), every other value is passed through
    **uncoerced**. This is deliberate: a plotly (or ANY) output is arbitrary user-component code
    output, so it must still be guarded/coerced - but that happens exactly once, inside the single
    ``enc_hook`` encode pass, instead of a separate pre-walk plus the encode.

    The returned dict therefore contains ``Raw`` (and possibly uncoerced) values and must be encoded
    with msgspec using ``enc_hook=to_jsonable_python`` - not dumped by pydantic. See
    ``hetdesrun.service.serialization_helpers.encode_workflow_execution_result``.
    """
    result = {}
    for outp_name, obj in output_results_by_output_name.items():
        raw_serializer = raw_pandas_serializer_funcs_by_type.get(
            data_type_map[output_types_by_output_name[outp_name]]
        )
        if raw_serializer is not None:
            result[outp_name] = raw_serializer(obj)
        else:
            result[outp_name] = obj
    return result


class NamedDataTypedValue(TypedDict):
    name: str
    type: DataType  # noqa: A003
    value: Any


def parse_via_pydantic(
    entries: list[NamedDataTypedValue],
    type_map: dict[DataType | None, type] | dict[DataType | None, UnionType] | None = None,
    null_str_to_None: bool = False,
) -> Any:
    """Parse data dynamically into a pydantic object

    Optionally a type_map can be specified which differs from the default data_type_map

    Returns an instantiated pydantic object if no parsing exception is thrown.

    May raise the typical exceptions of pydantic parsing.

    null_str_to_None converts value strings "null" to None before injecting into the Pydantic
    model __init__. This is necessary in order to allow entering null. E.g. consider the
    a int | None type annotation of a model field. Pydantic will happily interpret
    None, 42, "42" correctly but not try to interpret non-int-interpretable strings like
    "null" as None for values in the init method.
    """
    type_dict: dict[str, tuple[type | UnionType, "ellipsis"]] = {  # noqa: F821, UP037
        entry["name"]: (
            type_map[entry["type"]]
            if type_map is not None
            else data_type_map[entry["type"]],  # default to data_type_map
            ...,
        )
        for entry in entries
    }

    DynamicModel = create_model(
        "DynamicModel",
        **type_dict,
        __config__=ConfigDict(arbitrary_types_allowed=True, coerce_numbers_to_str=True),
    )  # type: ignore

    dyn_obj = DynamicModel(  # type: ignore
        **{
            entry["name"]: (
                entry["value"]
                if (
                    not null_str_to_None
                    or not isinstance(entry["value"], str)
                    or entry["value"] != "null"
                )
                else None
            )
            for entry in entries
        }
    )
    return dyn_obj


def parse_dict_using_data_type_dict(
    data_obj_dict: dict[str, Any],
    data_type_dict: dict[str, DataType],
    nullable: bool = False,
) -> dict[str, Any]:
    entries: list[NamedDataTypedValue] = [
        {"name": key, "type": data_type_dict[key], "value": data_obj}
        for key, data_obj in data_obj_dict.items()
    ]

    parsed_objects = dict(
        parse_via_pydantic(
            entries,
            type_map=data_type_map if nullable is False else optional_data_type_map,
            null_str_to_None=nullable,  # interpretation of "null" string values as None
        )
    )

    return parsed_objects


def parsing_not_identical(
    data_obj_dict: dict[str, Any],
    data_type_dict: dict[str, DataType],
    nullable: bool = False,
) -> dict[str, tuple[str, str]]:
    """Get keys for which parsed object is not identical to the input object

    Parsing according to Datatypes should be idempotent. So if an object is already
    correctly parsed, parsing should be the identity operation and preserve id(..).

    For a dict of objects and corresponding dict of DataTypes this function returns a dict
    containing those keys for which parsing is not the identity, and as value a tuple with first
    entry the actual received object type as string and as second entry the expected hetida designer
    DataType.

    Therefore this function can be used to determine if user produced objects have the correct
    type (i.e. the returned dict is empty!)

    Raises pydantic.ValidationError if parsing fails!
    """
    parsed_objects = parse_dict_using_data_type_dict(data_obj_dict, data_type_dict, nullable)

    not_identical = {
        key: (str(type(data_obj_dict[key])), str(data_type_dict[key]))
        for key, parsed_obj in parsed_objects.items()
        if id(parsed_obj) != id(data_obj_dict[key])
    }

    return not_identical


def parse_dynamically_from_datatypes(
    entries: list[NamedDataTypedValue], nullable: bool = False
) -> Any:
    return parse_via_pydantic(
        entries,
        type_map=data_type_map if nullable is False else optional_data_type_map,
        null_str_to_None=nullable,  # interpretation of "null" string values as None
    )


def parse_single_value_dynamically(
    name: str, value: Any, data_type: DataType, nullable: bool
) -> Any:
    return dict(
        parse_dynamically_from_datatypes(
            [{"name": name, "type": data_type, "value": value}], nullable
        )
    )[name]


def parse_value(value: Any, data_type_str: str, nullable: bool) -> Any:
    return parse_single_value_dynamically("some_value", value, DataType(data_type_str), nullable)


def parse_obj_as_type(obj: Any, target_type: type) -> Any:
    """Parse a type, e.g. Pydantic Custom Data Type

    Unfortunately defining a Pydantic Custom Data Type using Annotated and a BeforeValidator
    will only invoke this BeforeValidator if it is a field of another model. If you call
    it directly on an input object like MyPydanticCustomDataTypeWithBeforeValidator("test"),
    the BeforeValidator will never be called.

    This function is a workaround to this problem
    """

    DynamicModel = create_model(
        "DynamicModel",
        value=(target_type, ...),
        __config__=ConfigDict(arbitrary_types_allowed=True, coerce_numbers_to_str=True),
    )

    return DynamicModel(value=obj).value  # type: ignore


def parse_default_value(component_info: dict, input_name: str) -> Any:
    """Parse default value from COMPONENT_INFO dict

    Used in component main function header to parse a default
    value from the COMPONENT_INFO dict for an input.
    """
    inp = component_info["inputs"][input_name]
    return parse_value(inp["default_value"], inp["data_type"], True)


def plotly_fig_to_json_dict(
    fig: Figure, add_config_settings: bool = True, update_x_axes_tickformat: bool = True
) -> Any:
    """Turn Plotly figure into a Python dict-like object

    This function can be used in visualization components to obtain the
    correct plotly json-like object from a Plotly Figure object.

    See visualization components from the accompanying base components for
    examples on usage.
    """

    plot_target_settings = get_plot_target_settings()

    if update_x_axes_tickformat and plot_target_settings.datetime_tick_format is not None:
        fig.update_xaxes(tickformat=plot_target_settings.datetime_tick_format)

    fig_dict_obj = serialize_plotly_fig(fig)

    if "config" not in fig_dict_obj:
        fig_dict_obj["config"] = {}

    if add_config_settings and plot_target_settings.plot_target_locale is not None:
        fig_dict_obj["config"]["locale"] = plot_target_settings.plot_target_locale

    return fig_dict_obj


def extract_sub_value(data: dict[str, Any], json_path: list[str]) -> Any | None:
    """Extract a sub value of a nested dict structure

    Returns either the found value, or None if it could not be found.
    """
    current: Any | None = data
    for key in json_path:
        if isinstance(current, dict):
            current = current.get(key)
            if current is None:
                return None
        else:
            return None
    return current


def extract_sub_mapping(
    dict_of_metadata: dict[str | int, dict[str, Any]], json_path: list[str]
) -> dict[str | int, Any]:
    return {
        main_key: extract_sub_value(sub_dict, json_path)
        for main_key, sub_dict in dict_of_metadata.items()
    }


def add_columns_from_metric_metadata(
    multitsframe: pd.DataFrame,
    keys: list[str | list[str]] | None = None,
    replace_metric_col_with_key: str | list[str] | None = None,
    default_value: Any = np.nan,
) -> pd.DataFrame:
    """Add columns (or replace metric column) from attrs metadata in a multitsframe

    Expects a hetida designer multitsframe with metadata according to hetida designer
    metadata conventions.

    For replacing the metric col using replace_metric_col_with_key this expects a
    value for each metric to be found in the metadata. If that is not the case it keeps
    the existing metric entry!

    For adding columns, a default_value can be specified that is used when no entry for
    a key is found in the metadata for the corresponding metric.

    Modifies in-place, but also returns the modified multitsframe.

    keys is a list of json-path-like lists. For each entry a column is added, where
    in the found metric metdata the field at subpath defined by this entry is assigned.
    For convenience a str entry is interpreted as json path of length 1.

    E.g. if your attrs looks like
        "by_metric": {
            "a": {
                "structured_metadata": {
                    "metric": {  # metadata associated to the current metric. These are
                        "name": "AAAAA",
                        "display_name": "some A",
                        "short_display_name": "a",
                        "description": "some descriptions",
                        "external_id": "AA",
                        "channel_id": "abc123-...",
                    }
                }
            },
            "b": {
                "structured_metadata": {
                    "metric": {  # metadata associated to the current metric. These are
                        "name": "BBBBB",
                        "display_name": "some B",
                        "short_display_name": "b",
                        "description": "some descriptions",
                        "external_id": "BB",
                        "channel_id": "abc123-...",
                    }
                }
            },
        }

    then you can specify to add an external_id column and an additional channel id column via
        add_columns_from_metric_metadata(
            multitsframe, keys=[
                ["structured_metadata", "metric", "external_id"],
                ["structured_metadata", "metric", "channel_id"]
            ]
        )

    Similarly replace_metric_col_with_key is a json-path-like list or interpreted as length 1 such
    path if a single str.
    """

    metrics_metadata = extract_sub_value(multitsframe.attrs, ["by_metric"])

    if metrics_metadata is None or all(
        (x is None or len(x) == 0)
        for x in metrics_metadata.values()  # nothin contained in the values
    ):
        metrics_metadata = extract_sub_value(multitsframe.attrs, ["metric_metadata"])

    if metrics_metadata is None:
        logger.warning("Did not found metric metadata for extracting data into columns.")
        return multitsframe

    if replace_metric_col_with_key is not None:
        key_list = (
            [replace_metric_col_with_key]
            if isinstance(replace_metric_col_with_key, str)
            else replace_metric_col_with_key
        )

        multitsframe["metric"] = multitsframe["metric"].replace(
            extract_sub_mapping(metrics_metadata, key_list)  # type: ignore
        )
    if keys is not None:
        for key in keys:
            key_list = [key] if isinstance(key, str) else key

            mapping_dict = extract_sub_mapping(metrics_metadata, key_list)  # type: ignore

            mapping_dict = defaultdict(lambda: default_value, mapping_dict)

            multitsframe[key_list[-1]] = multitsframe["metric"].map(mapping_dict)

    return multitsframe
