[pytest]
filterwarnings =
    ignore:.*utcnow.*is deprecated and scheduled for removal in a future version.*:DeprecationWarning
    ignore:pkg_resources is deprecated as an API:UserWarning
    ignore::pytest.PytestUnraisableExceptionWarning


asyncio_mode=strict