[pytest]
filterwarnings =
    ignore:.*asyncio.*iscoroutinefunction.*deprecated.*:DeprecationWarning:asyncstdlib
    # tests deliberately use small RSA keys for speed, see gen_rs256_key_pair
    ignore:Key size should be >= 2048 bits:Warning

asyncio_mode=strict
markers = 
    performance: marks tests that ensure performance (run with --ensure-performance)
