#!/usr/bin/env bash

usage() {
    echo "$0 [COMMAND] [ARGS]"
    echo ""
    echo "Hint: All commands expect a Python dev virtual environment to be active"
    echo ""
    echo "  Commands:"
    echo "  - deps:upgrade    :    resolves and locks Python dependencies, upgrading them all"
    echo "  - deps:sync       :    syncs currently activated virtual environment with locked Python dev dependencies."
    echo "  - shell           :    Activate virtual environment, thereby creating and syncing if necessary"
    echo "  - test            :    run pytest on hetdesrun code"
    echo "  - lint            :    call ruff"
    echo "  - typecheck       :    run mypy static type check"
    echo "  - format          :    run ruff format"
    echo "  - check           :    run format check, tests, typechecking"
    echo "  - build_package   :    build hdhelpers package"
}

fn_exists() {
    LC_ALL=C type "${1:-}" 2>/dev/null | grep -q 'function'
}

COMMAND="${1:-}"
shift
ARGUMENTS=("${@}")

set -euo pipefail

#----- subcommands -----#

deps:upgrade() {
    # upgrade and lock including dev-dependencies
    ./pipt upgrade
}

deps:sync() {
    # sync dev dependencies
    ./pipt sync
}

shell() {
    ./pipt shell
}

test() {
    python -m pytest --cov=hetdesrun --no-cov-on-fail --cov-report=term-missing tests "$@"
    python -m pytest --cov=hdhelpers --no-cov-on-fail --cov-report=term-missing hdhelpers -c hdhelpers/pytest.ini
}

# test_components() {
#     python -m pytest --doctest-modules components
# }

lint() {
    ruff check hdhelpers hetdesrun transformations/components tests "${@}"
}

imsort() {
    ruff check --select I hdhelpers hetdesrun transformations/components tests --fix "${@}"
}

typecheck() {
    python3 -m mypy "${@}" hdhelpers hetdesrun
}

format() {
    ruff check --select I hdhelpers hetdesrun transformations/components tests --fix "${@}" && echo "--> Ruff import sorting run."
    ruff format hdhelpers hetdesrun transformations/components tests "${@}" && echo "--> ruff format run."
}

seccheck() {
    bandit -r hetdesrun --skip B101
}

check() {
    # Will fail with non-zero exit status if any tool has some complaint.
    # If everything is okay this will have 0 exits status
    echo "--> Running ruff format in check mode" && ruff format hetdesrun transformations/components tests --check &&
        echo "--> Running tests" && python -m pytest --cov=hetdesrun --cov-report=term-missing tests &&
        echo "--> Running mypy" && mypy hetdesrun &&
        echo "--> Running ruff" && ruff check hetdesrun transformations/components tests &&
        echo "--> Running bandit" && bandit -r hetdesrun --skip B101 &&
        echo "CHECKS EXECUTION RESULTS: All checks were successful!"
}

export_api_html() {
    python extract_openapi_html.py "${@}"
}

build_package(){
    uv build hdhelpers
    find hdhelpers/dist -name "*.whl" | xargs pip install --no-cache-dir --force-reinstall --no-deps
}

#----- Execution -----#

if fn_exists "$COMMAND"; then
    # cd into the script's current directory
    cd "${0%/*}" || exit 1

    # Execute
    TIMEFORMAT=$'\nTask completed in %3lR'

    time "$COMMAND" "${ARGUMENTS[@]}"
else
    usage
fi
