"""add release wiring

Revision ID: aaf97187894d
Revises: 99f61ce50ad5
Create Date: 2024-09-05 11:16:12.691137

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = "aaf97187894d"
down_revision = "99f61ce50ad5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("transformation_revisions", sa.Column("release_wiring", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("transformation_revisions", "release_wiring")
    # ### end Alembic commands ###
